services:
  # Backend Service
  - type: web
    name: productivity-social-backend
    env: java
    buildCommand: cd backend && mvn clean package -DskipTests
    startCommand: cd backend && java -jar target/*.jar
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 86400000
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: LOG_LEVEL
        value: INFO
      - key: PORT
        value: 8080
    healthCheckPath: /api/auth/health

  # Frontend Service
  - type: web
    name: productivity-social-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm install -g serve && serve -s build -l $PORT
    envVars:
      - key: REACT_APP_API_URL
        sync: false
